"""empty message

Revision ID: 19892401a6aa
Revises: f65a2417dd7c
Create Date: 2026-05-24 17:27:02.642807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19892401a6aa'
down_revision = 'f65a2417dd7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_from_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_to_id'], ['id'])

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
